const db = require('../dbSetup');

module.exports = {

    getAllLocationsForUser: function (userID) {

        return new Promise(resolve =>  {

             console.log( "user id = " + userID)
             userID = userID; 

            db.query('SELECT * FROM locations WHERE user_id=$1', [userID], function (err, result) {
               let json = JSON.stringify(result.rows);  
                console.log(json);
                resolve(json);
            });


        })
       
    }, 
    createLocation: function (userID, newLocation) {

        return new Promise(resolve =>  {
            let loc_name = newLocation["name"];
            let details = newLocation["details"];

            console.log("Creating Location: ( name: " + loc_name + " details: " + details + " UserID: "+ userID + ")");

            db.query('INSERT INTO LOCATIONS (user_id, location_name, description) VALUES ($1,$2,$3)', [userID, loc_name, details], function (err, result) {
               console.log(result);
               console.log(err);
                //Currently not sure how to GET location_id after it was generated by this INSERT!  Just return this as a result
                resolve("Location Created");
            });


        })
       
    }
}